@extends('admin.layout')
@section('title', 'Payslip')

@section('actions')
<button onclick="window.print()" class="px-5 py-2.5 rounded-lg text-sm border border-white/15 text-stone-300 hover:border-gold">🖨 Print</button>
@endsection

@section('content')
<div id="slip" class="max-w-2xl mx-auto rounded-xl border border-white/10 bg-ink-800 p-8">
  <div class="flex items-start justify-between mb-8">
    <div class="flex items-center gap-3">
      <img src="{{ asset('assets/soniyo-logo.png') }}" onerror="this.onerror=null;this.src='{{ asset('assets/soniyo-emblem.svg') }}'" class="h-14 w-auto">
      <div>
        <div class="serif text-2xl text-gold-soft">SoNiYo Beauty Salon</div>
        <div class="text-xs text-stone-500">{{ \App\Models\SiteSetting::get('contact_address','148 Madison Avenue') }}</div>
      </div>
    </div>
    <div class="text-right">
      <div class="serif text-xl text-stone-100">PAYSLIP</div>
      <div class="text-xs text-stone-400">{{ $slip->period_label }}</div>
    </div>
  </div>

  <div class="flex justify-between text-sm mb-6">
    <div>
      <div class="text-[10px] uppercase tracking-wider text-stone-500 mb-1">Employee</div>
      <div class="text-stone-100">{{ $slip->staff->name ?? '—' }}</div>
      <div class="text-stone-500 text-xs">{{ $slip->staff->title }}</div>
    </div>
    <div class="text-right">
      <div class="text-[10px] uppercase tracking-wider text-stone-500 mb-1">Status</div>
      <div class="{{ $slip->status==='paid' ? 'text-emerald-300' : 'text-gold-soft' }}">{{ ucfirst($slip->status) }}{{ $slip->paid_at ? ' · '.$slip->paid_at->format('M d, Y') : '' }}</div>
    </div>
  </div>

  <table class="w-full text-sm mb-6">
    <tbody class="divide-y divide-white/5">
      <tr><td class="py-2 text-stone-400">Base Salary</td><td class="py-2 text-right text-stone-200">₹{{ number_format($slip->base_salary,2) }}</td></tr>
      <tr><td class="py-2 text-stone-400">Commission <span class="text-xs text-stone-600">(svc ₹{{ number_format($slip->service_revenue,0) }} + prod ₹{{ number_format($slip->product_revenue,0) }})</span></td><td class="py-2 text-right text-gold-soft">₹{{ number_format($slip->commission_amount,2) }}</td></tr>
      <tr><td class="py-2 text-stone-400">Target Bonus</td><td class="py-2 text-right text-emerald-300">₹{{ number_format($slip->target_bonus,2) }}</td></tr>
      <tr><td class="py-2 text-stone-400">Incentive / Tips</td><td class="py-2 text-right text-stone-200">₹{{ number_format($slip->incentive,2) }}</td></tr>
      <tr><td class="py-2 text-stone-400">Deduction</td><td class="py-2 text-right text-rose-300">−₹{{ number_format($slip->deduction,2) }}</td></tr>
    </tbody>
  </table>

  <div class="ml-auto w-64 text-sm space-y-1">
    <div class="flex justify-between text-stone-400"><span>Gross</span><span>₹{{ number_format($slip->gross,2) }}</span></div>
    <div class="flex justify-between text-xl text-gold-soft serif border-t border-white/10 pt-2"><span>Net Pay</span><span>₹{{ number_format($slip->net,2) }}</span></div>
  </div>

  @if($slip->notes)<p class="text-xs text-stone-500 mt-6">Note: {{ $slip->notes }}</p>@endif
  <p class="text-center text-xs text-stone-500 mt-8">Generated by SoNiYo Salon Management ✦</p>
</div>

<style>@media print{aside,header,.totop{display:none!important}#slip{border:none}body{background:#fff}}</style>
@endsection
